version: '3'

volumes:
  secpickupvolume:
    driver: local

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    options: >-
      --name sonarqube
      -e SONARQUBE_JDBC_URL=jdbc:h2:tcp://sonarqube:9092/sonar
      -e SONARQUBE_JDBC_USERNAME=sonar
      -e SONARQUBE_JDBC_PASSWORD=sonar

  # mysql server
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: aod
      MYSQL_DATABASE: secpickup
      MYSQL_PASSWORD: pass
    volumes:
      - 'secpickupvolume:/data'
