spring:
  datasource:
    username: aod
    password: pass
    url: jdbc:mysql://localhost:3306/secpickup?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQLDialect
#
#jpa:
#  hibernate:
#    ddl-auto: update
#  show-sql: true
#  properties:
#    hibernate:
#      ddl-auto: update
server:
  address: 0.0.0.0
  port: 8080
  error:
    include-message: always
