# mail config
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_ID: ayouboudada13@gmail.com
MAIL_PASSWORD: dekd pfrf bgvq uyxh

# db config
DB_USERNAME: aod
DB_PASSWORD: pass
DB_NAME: secpickup

# server config
SERVER_PORT: 8080
